<a href="https://colab.research.google.com/github/Naveen148/Naveen148/blob/main/project_interpret.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv("/content/train-chennai-sale.csv")

In [ ]:
print(df.columns)
df

Index(['AREA', 'INT_SQFT', 'DATE_SALE', 'DIST_MAINROAD', 'N_BEDROOM',
       'N_BATHROOM', 'N_ROOM', 'SALE_COND', 'PARK_FACIL', 'DATE_BUILD',
       'BUILDTYPE', 'UTILITY_AVAIL', 'STREET', 'MZZONE', 'QS_ROOMS',
       'QS_BATHROOM', 'QS_BEDROOM', 'QS_OVERALL', 'SALES_PRICE',
       'AGE_BUILDING'],
      dtype='object')


AREA  INT_SQFT  DATE_SALE  DIST_MAINROAD  N_BEDROOM  N_BATHROOM  N_ROOM  \
0        4      1004       2011            131        1.0         1.0       3   
1        1      1986       2006             26        2.0         1.0       5   
2        0       909       2012             70        1.0         1.0       3   
3        6      1855       2010             14        3.0         2.0       5   
4        4      1226       2009             84        1.0         1.0       3   
...    ...       ...        ...            ...        ...         ...     ...   
7104     4       598       2011             51        1.0         1.0       2   
7105     6      1897       2004             52        3.0         2.0       5   
7106     6      1614       2006            152        2.0         1.0       4   
7107     4       787       2009             40        1.0         1.0       2   
7108     6      1896       2005            156        3.0         2.0       5   

      SALE_COND  PARK_FACIL  DATE_BUILD  BUILDTYPE  UTILITY_AVAIL  STREET  \
0             0           2        1967          0              0       2   
1             0           0        1995          0              0       0   
2             0           2        1992          0              1       0   
3             2           0        1988          2              2       2   
4             0           2        1979          2              0       0   
...         ...         ...         ...        ...            ...     ...   
7104          1           0        1962          2              1       1   
7105          2           2        1995          2              2       1   
7106          3           0        1978          1              2       0   
7107          4           2        1977          0              1       2   
7108          4           2        1961          2              1       2   

      MZZONE  QS_ROOMS  QS_BATHROOM  QS_BEDROOM  QS_OVERALL  SALES_PRICE  \
0          0       4.0          3.9         4.9       4.330      7600000   
1          3       4.9          4.2         2.5       3.765     21717770   
2          4       4.1          3.8         2.2       3.090     13159200   
3          2       4.7          3.9         3.6       4.010      9630290   
4          1       3.0          2.5         4.1       3.290      7406250   
...      ...       ...          ...         ...         ...          ...   
7104       5       3.0          2.2         2.4       2.520      5353000   
7105       3       3.6          4.5         3.3       3.920     10818480   
7106       2       4.3          4.2         2.9       3.840      8351410   
7107       4       4.6          3.8         4.1       4.160      8507000   
7108       2       3.1          3.5         4.3       3.640      9976480   

      AGE_BUILDING  
0               44  
1               11  
2               20  
3               22  
4               30  
...            ...  
7104            49  
7105             9  
7106            28  
7107            32  
7108            44  

[7056 rows x 20 columns]

In [ ]:
del df['PRT_ID']
del df['COMMIS']
del df['REG_FEE']

In [ ]:
df.isnull().sum()

AREA              0
INT_SQFT          0
DATE_SALE         0
DIST_MAINROAD     0
N_BEDROOM         1
N_BATHROOM        5
N_ROOM            0
SALE_COND         0
PARK_FACIL        0
DATE_BUILD        0
BUILDTYPE         0
UTILITY_AVAIL     0
STREET            0
MZZONE            0
QS_ROOMS          0
QS_BATHROOM       0
QS_BEDROOM        0
QS_OVERALL       48
SALES_PRICE       0
dtype: int64

In [ ]:
df = df.dropna(subset = ['QS_OVERALL'] )
df = df.dropna(subset = ['N_BEDROOM'] )
df = df.dropna(subset = ['N_BATHROOM'])

In [ ]:
df.DATE_BUILD = pd.DatetimeIndex(df.DATE_BUILD).year
df.DATE_SALE = pd.DatetimeIndex(df.DATE_SALE).year
df['AGE_BUILDING']= (df.DATE_SALE - df.DATE_BUILD)
df.head()

AREA  INT_SQFT  DATE_SALE  DIST_MAINROAD  N_BEDROOM  N_BATHROOM  \
0  Karapakkam      1004       2011            131        1.0         1.0   
1  Anna Nagar      1986       2006             26        2.0         1.0   
2       Adyar       909       2012             70        1.0         1.0   
3   Velachery      1855       2010             14        3.0         2.0   
4  Karapakkam      1226       2009             84        1.0         1.0   

   N_ROOM SALE_COND PARK_FACIL  DATE_BUILD   BUILDTYPE UTILITY_AVAIL  STREET  \
0       3  AbNormal        Yes        1967  Commercial        AllPub   Paved   
1       5  AbNormal         No        1995  Commercial        AllPub  Gravel   
2       3  AbNormal        Yes        1992  Commercial           ELO  Gravel   
3       5    Family         No        1988      Others       NoSewr    Paved   
4       3  AbNormal        Yes        1979      Others        AllPub  Gravel   

  MZZONE  QS_ROOMS  QS_BATHROOM  QS_BEDROOM  QS_OVERALL  SALES_PRICE  \
0      A       4.0          3.9         4.9       4.330      7600000   
1     RH       4.9          4.2         2.5       3.765     21717770   
2     RL       4.1          3.8         2.2       3.090     13159200   
3      I       4.7          3.9         3.6       4.010      9630290   
4      C       3.0          2.5         4.1       3.290      7406250   

   AGE_BUILDING  
0            44  
1            11  
2            20  
3            22  
4            30

In [ ]:
mappings = {'Chrompt':'Chrompet', 'Chrmpet':'Chrompet', 'Chormpet':'Chrompet','Karapakam':'Karapakkam','KKNagar':'KK Nagar',
           'Velchery':'Velachery','Ana Nagar':'Anna Nagar','Ann Nagar':'Anna Nagar','Adyr':'Adyar','TNagar':'T Nagar'}

In [ ]:
df['AREA'] = df['AREA'].replace(mappings)
df['AREA'].unique()

array(['Karapakkam', 'Anna Nagar', 'Adyar', 'Velachery', 'Chrompet',
       'KK Nagar', 'T Nagar'], dtype=object)

In [ ]:
mappings = {'AdjLand': 'Adj Land', 
            'Adj Land':'Adj Land',
            'Normal Sale': 'Normal Sale',
            'Partial': 'Partial',
            'Partiall': 'Partial',
            'PartiaLl': 'Partial',
            'AbNormal':'AbNormal',
            'Ab Normal':'AbNormal',
            'Family':'Family'}

In [ ]:
df['SALE_COND'] = df['SALE_COND'].replace(mappings)
df['SALE_COND'].unique()

array(['AbNormal', 'Family', 'Partial', 'Adj Land', 'Normal Sale'],
      dtype=object)

In [ ]:
mappings={'Commercial':'Comercial',
          'Others':'Other',
         } 

In [ ]:
df['BUILDTYPE'] = df['BUILDTYPE'].replace(mappings)
df['BUILDTYPE'].unique()

array(['Comercial', 'Other', 'House'], dtype=object)

In [ ]:
mappings={'Pavd':'Paved',
          'No Access':'NoAccess'}

In [ ]:
df['STREET'] = df['STREET'].replace(mappings)
df['STREET'].unique()

array(['Paved', 'Gravel', 'NoAccess'], dtype=object)

In [ ]:
mappings={'AllPub':'All Pub',
          'NoSeWa':'NoSewr',
          'NoSewr ':'NoSewr'
         } 

In [ ]:
df['UTILITY_AVAIL'] = df['UTILITY_AVAIL'].replace(mappings)
df['UTILITY_AVAIL'].unique()

array(['All Pub', 'ELO', 'NoSewr'], dtype=object)

In [ ]:
from sklearn import preprocessing


label_encoder = preprocessing.LabelEncoder()


df['BUILDTYPE']= label_encoder.fit_transform(df['BUILDTYPE'])

df['BUILDTYPE'].unique()

array([0, 2, 1])

In [ ]:
from sklearn import preprocessing


label_encoder = preprocessing.LabelEncoder()


df['UTILITY_AVAIL']= label_encoder.fit_transform(df['UTILITY_AVAIL'])

df['UTILITY_AVAIL'].unique()

array([0, 1, 2])

In [ ]:
from sklearn import preprocessing


label_encoder = preprocessing.LabelEncoder()


df['MZZONE']= label_encoder.fit_transform(df['MZZONE'])

df['MZZONE'].unique()

array([0, 3, 4, 2, 1, 5])

In [ ]:
from sklearn import preprocessing


label_encoder = preprocessing.LabelEncoder()


df['STREET']= label_encoder.fit_transform(df['STREET'])

df['STREET'].unique()

array([2, 0, 1])

In [ ]:
from sklearn import preprocessing


label_encoder = preprocessing.LabelEncoder()


df['SALE_COND']= label_encoder.fit_transform(df['SALE_COND'])

df['SALE_COND'].unique()

array([0, 2, 4, 1, 3])

In [ ]:
from sklearn import preprocessing


label_encoder = preprocessing.LabelEncoder()


df['AREA']= label_encoder.fit_transform(df['AREA'])

df['AREA'].unique()

array([4, 1, 0, 6, 2, 3, 5])

In [ ]:
from sklearn import preprocessing


label_encoder = preprocessing.LabelEncoder()


df['PARK_FACIL']= label_encoder.fit_transform(df['PARK_FACIL'])

df['PARK_FACIL'].unique()

array([2, 0, 1])

In [ ]:
df.dtypes

AREA               int64
INT_SQFT           int64
DATE_SALE          int64
DIST_MAINROAD      int64
N_BEDROOM        float64
N_BATHROOM       float64
N_ROOM             int64
SALE_COND          int64
PARK_FACIL         int64
DATE_BUILD         int64
BUILDTYPE          int64
UTILITY_AVAIL      int64
STREET             int64
MZZONE             int64
QS_ROOMS         float64
QS_BATHROOM      float64
QS_BEDROOM       float64
QS_OVERALL       float64
SALES_PRICE        int64
AGE_BUILDING       int64
dtype: object

In [ ]:
del df['DATE_BUILD']

In [ ]:
del df['DATE_SALE']

In [ ]:
X = df.drop('SALES_PRICE',axis=1).values
y = df.SALES_PRICE.values

In [ ]:
del df['AREA']
del df['DIST_MAINROAD']
del df['UTILITY_AVAIL']

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler

std = StandardScaler()
X_train = std.fit_transform(X_train)
X_test = std.transform(X_test)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

In [ ]:
rf = RandomForestRegressor(n_estimators= 100, max_depth = 20, max_features='sqrt')
rf.fit(X_train, y_train);

In [ ]:
predictions = rf.predict(X_test)

In [ ]:
r2_score(predictions, y_test)

0.9712936530925187

In [ ]:
from sklearn import tree

In [ ]:
from sklearn.tree import export_graphviz
import pydot

In [ ]:
tree = rf.estimators_[5]

In [ ]:
print('The depth of this tree is:', tree.tree_.max_depth)

The depth of this tree is: 20


In [ ]:
rf_small = RandomForestRegressor(n_estimators=10, max_depth = 20, random_state=42)
rf_small.fit(X_train, y_train)

RandomForestRegressor(max_depth=20, n_estimators=10, random_state=42)

In [ ]:
tree_small = rf_small.estimators_[5]

In [ ]:
export_graphviz(tree_small, out_file = 'small_tree.dot',  rounded = True, precision = 1)

In [ ]:
(graph, ) = pydot.graph_from_dot_file('small_tree.dot')

In [ ]:
graph.write_png('small_tree.png');

In [ ]:
# Get numerical feature importances
importances = list(rf.feature_importances_)

# List of tuples with variable and importance
feature_importances = [(feature, round(importance, 2)) for feature, importance in zip(df, importances)]

# Sort the feature importances by most important first
feature_importances = sorted(feature_importances, key = lambda x: x[1], reverse = True)

# Print out the feature and importances 
[print('Variable: {:20} Importance: {}'.format(*pair)) for pair in feature_importances];

Variable: MZZONE               Importance: 0.3
Variable: N_BEDROOM            Importance: 0.21
Variable: PARK_FACIL           Importance: 0.16
Variable: QS_BEDROOM           Importance: 0.1
Variable: INT_SQFT             Importance: 0.08
Variable: N_ROOM               Importance: 0.05
Variable: SALE_COND            Importance: 0.02
Variable: N_BATHROOM           Importance: 0.01
Variable: BUILDTYPE            Importance: 0.01
Variable: STREET               Importance: 0.01
Variable: QS_BATHROOM          Importance: 0.01
Variable: QS_OVERALL           Importance: 0.01
Variable: SALES_PRICE          Importance: 0.01
Variable: AGE_BUILDING         Importance: 0.01
Variable: QS_ROOMS             Importance: 0.0


In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
import xgboost as xgb
from sklearn.model_selection import cross_val_score
import numpy as np
for lr in [0.01,0.02,0.03,0.04,0.05,0.06,0.07,0.08,0.09,0.1,0.11,0.12,0.13,0.14,0.15,0.2,0.5,0.7,1]:
  model = xgb.XGBRegressor(learning_rate = lr, n_estimators=100, verbosity = 0) # initialise the model
  model.fit(X_train,y_train) #train the model
  model.score(X_test, y_test) # scoring the model - r2 squared
  print("Learning rate : ", lr, " Train score : ", model.score(X_train,y_train), " Cross-Val score : ", np.mean(cross_val_score(model, X_train, y_train, cv=10)))

Learning rate :  0.01  Train score :  -0.4000791378006012  Cross-Val score :  -0.4064753190724125
Learning rate :  0.02  Train score :  0.7203109582656141  Cross-Val score :  0.7158766120276635
Learning rate :  0.03  Train score :  0.899878108851452  Cross-Val score :  0.8963742396396663
Learning rate :  0.04  Train score :  0.9432701956558598  Cross-Val score :  0.939510782614412
Learning rate :  0.05  Train score :  0.9596601510790601  Cross-Val score :  0.9574359968314987
Learning rate :  0.06  Train score :  0.9710262372647345  Cross-Val score :  0.9670526681353054
Learning rate :  0.07  Train score :  0.9769652860519917  Cross-Val score :  0.9733747209040647
Learning rate :  0.08  Train score :  0.9803393635226929  Cross-Val score :  0.9780701647774253
Learning rate :  0.09  Train score :  0.9837533580639478  Cross-Val score :  0.9814211272352227
Learning rate :  0.1  Train score :  0.9863452801362682  Cross-Val score :  0.9845624222672115
Learning rate :  0.11  Train score :  0.9

In [ ]:
model = xgb.XGBRegressor(learning_rate = 0.5, n_estimators=100)
model.fit(X_train,y_train) #train the model
model.score(X_test, y_test) # scoring the model - r2 squared

[06:04:47] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


0.9931763524634937